'use client';
import {useState}from 'react';
import {Plus,Download,Wallet}from 'lucide-react';
import {Button}from '@/components/ui/button';
import {Input}from '@/components/ui/input';
import {Textarea}from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger}from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription}from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription}from '@/components/ui/sheet';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell}from '@/components/ui/table';
import type{Workspace,ReportScope,Lead,Stage,Payment}from '@/lib/types';
import {visibleLeads,leadSource,report,groupReport,campaigns,netPayment}from '@/lib/reporting';
import {millis}from '@/lib/attribution';
import {Picker,ModeNote,money,number,stages,download}from './common';
export default function Leads({data,mutate,scope,setScope}:{data:Workspace;mutate:(a:string,v:unknown)=>Promise<unknown>;scope:ReportScope;setScope:(s:ReportScope)=>void}){
 const mode=scope.mode==='all'?'demo':scope.mode;
 const[view,setView]=useState('leads'),[selected,setSelected]=useState<Lead|null>(null),[payment,setPayment]=useState<Payment|null>(null),[newLead,setNewLead]=useState(false),[owner,setOwner]=useState(''),[newCourse,setNewCourse]=useState(data.courses[0]),[sourceId,setSource]=useState('unknown'),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[refund,setRefund]=useState<{id:string;amount:number}|null>(null);
 const r=report(data,scope,{model:'last',windowDays:7,halfLifeDays:2,family:false,paymentOffset:0}),groups=groupReport(r,'campaignCourse'),allLeads=visibleLeads(data,scope),cmap=new Map(campaigns(data,mode).map(c=>[c.id,c.name]));
 const leads=allLeads.filter(l=>!query||(l.id+' '+l.course+' '+l.owner+' '+(cmap.get(leadSource(data,l,scope.asOf)?.campaignId??'')??'')).toLowerCase().includes(query.toLowerCase()));
 const paymentIds=new Set(r.rows.map(a=>a.paymentId)),payments=data.payments.filter(p=>p.mode===mode&&millis(p.at)<=millis(scope.asOf+'T23:59:59Z')&&(paymentIds.has(p.id)||leads.some(l=>l.userId===p.userId&&l.course===p.course))&&(!query||(p.id+' '+p.course+' '+p.leadId).toLowerCase().includes(query.toLowerCase())));
 function paymentDraft(l?:Lead){l??=leads[0];if(!l)return;setPayment({id:'pay_'+crypto.randomUUID().replaceAll('-','').slice(0,18),mode,userId:l.userId,leadId:l.id,course:l.course||data.courses[0],amount:8950,at:mode==='demo'?new Date(Math.max(Date.parse(l.createdAt),...data.events.filter(e=>e.mode===mode&&e.userId===l!.userId).map(e=>Date.parse(e.at)))+3600000).toISOString():new Date().toISOString(),source:'manual',status:'paid',refundAmount:0});}
 async function save(action:string,value:unknown,done:()=>void){setBusy(true);try{await mutate(action,value);done();}catch{}finally{setBusy(false);}}
 async function addLead(e:React.FormEvent){e.preventDefault();const id=crypto.randomUUID().replaceAll('-','').slice(0,18);await save('new_lead',{id:'lead_'+id,mode,userId:mode+'_manual_'+id,stage:'new',owner,course:newCourse,sourcePlacementId:sourceId==='unknown'?null:sourceId,note:sourceId==='unknown'?'Заявка добавлена вручную; источник неизвестен.':'Источник внесён менеджером со слов клиента.',createdAt:new Date().toISOString()},()=>setNewLead(false));}
 if(mode==='historical')return <><h1>Заявки и оплаты по курсам</h1><div className="info-strip"><p>В исходном кейсе есть оплаты, но нет заявок и их источников. Создавать исторические лиды из покупок нельзя. Выберите «Синтетическое демо» или «Новый запуск» для работы с заявками.</p></div><Button className="mt-5" onClick={()=>setScope({...scope,mode:'demo',channels:null,campaigns:null,from:'2026-09-12',to:'2026-09-23',asOf:'2026-09-30'})}>Открыть демо</Button></>;
 return <><div className="page-heading"><div><div className="eyebrow">ВОРОНКА ПО КУРСУ И КАМПАНИИ</div><h1>Заявки и оплаты</h1><p>Одна заявка — интерес одного посетителя к конкретному курсу. Источник оплаты рассчитывается по пути ссылок.</p></div><div className="actions"><Button variant="outline" onClick={()=>setNewLead(true)}><Plus size={16}/>Заявка вручную</Button><Button onClick={()=>paymentDraft()} disabled={!leads.length}><Wallet size={16}/>Оплата</Button></div></div><ModeNote mode={mode}/><section className="panel mt-5"><div className="panel-header"><div><h2>Воронка по кампаниям и курсам</h2><p>Нажмите кампанию, чтобы оставить только её заявки и оплаты.</p></div></div><Table><TableHeader><TableRow><TableHead>Кампания / курс</TableHead><TableHead>Заявки</TableHead><TableHead>Оплаченные заявки</TableHead><TableHead>Конверсия</TableHead><TableHead>Сумма по Last Touch</TableHead></TableRow></TableHeader><TableBody>{groups.map(g=><TableRow key={g.key}><TableCell><button className="table-cell-action" onClick={()=>setScope({...scope,campaigns:[...g.campaignIds].filter(id=>id!=='unknown').length?[...g.campaignIds]:null,courses:[...g.courses]})}>{g.name}</button><p className="muted">{g.detail}</p></TableCell><TableCell>{g.leads}</TableCell><TableCell>{g.cohortBuyers}</TableCell><TableCell>{g.conversion===null?'—':number(g.conversion)+'%'}</TableCell><TableCell>{money(g.netRevenue)}</TableCell></TableRow>)}</TableBody></Table></section>
 <div className="calendar-toolbar"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ID заявки, курс, кампания" aria-label="Поиск заявок" className="max-w-80"/><Tabs value={view} onValueChange={v=>setView(String(v))}><TabsList><TabsTrigger value="leads">Заявки · {leads.length}</TabsTrigger><TabsTrigger value="payments">Оплаты · {payments.length}</TabsTrigger></TabsList></Tabs></div>
 {view==='leads'?<><div className="overflow-x-auto"><div className="kanban">{stages.map(stage=><section key={stage.value} className="kanban-col"><div className="kanban-head"><span>{stage.label}</span><span>{leads.filter(l=>l.stage===stage.value).length}</span></div>{leads.filter(l=>l.stage===stage.value).map(l=>{const p=leadSource(data,l,scope.asOf);return <button className="lead-card" key={l.id} onClick={()=>setSelected({...l})}><strong>{l.id}</strong><p>{l.course||'Курс не выбран'}</p><p className="muted">{cmap.get(p?.campaignId??'')??'Источник неизвестен'}</p><p className="muted">{p?.channel??'Введено вручную'}</p><span className="pill neutral">{l.owner||'Не назначен'}</span></button>;})}</section>)}</div></div>{!leads.length&&<div className="empty">Нет заявок по этому выбору. Откройте уникальную ссылку размещения и отправьте форму, либо внесите заявку вручную.</div>}<Button variant="outline" className="mt-5" onClick={()=>download('leads-'+mode+'.csv',leads)}><Download size={16}/>CSV заявок</Button></>:<section className="panel"><div className="panel-header"><h2>Журнал подтверждённых оплат</h2><Button variant="outline" onClick={()=>download('payments-'+mode+'.csv',payments)}>CSV</Button></div><Table><TableHeader><TableRow><TableHead>Оплата / заявка</TableHead><TableHead>Курс</TableHead><TableHead>Источники по Last Touch</TableHead><TableHead>После возврата</TableHead><TableHead>Возврат</TableHead></TableRow></TableHeader><TableBody>{payments.map(p=><TableRow key={p.id}><TableCell>{p.id}<p className="muted">{p.leadId??data.leads.find(l=>l.userId===p.userId&&l.course===p.course)?.id??'Нет заявки'}</p></TableCell><TableCell>{p.course}<p className="muted">{p.at.slice(0,10)}</p></TableCell><TableCell>{r.all.filter(a=>a.paymentId===p.id).map(a=><p key={a.campaignId}>{cmap.get(a.campaignId)??'Неизвестно'} · {number(a.weight*100)}%</p>)}</TableCell><TableCell>{money(netPayment(p))}</TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>setRefund({id:p.id,amount:p.status==='refunded'?p.amount:p.refundAmount??0})}>{p.refundAmount?money(p.refundAmount):'Внести'}</Button></TableCell></TableRow>)}</TableBody></Table></section>}
 <div className="info-strip"><p>Заявка относится к первому источнику входа, а оплата распределяется выбранной моделью. Поэтому количество заявок кампании и доли оплат могут отличаться. Повторные покупки и курсные строки не считаются новыми клиентами автоматически.</p></div>
 <Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{selected?.id}</SheetTitle><SheetDescription>{selected?.course||'Уточните курс'}</SheetDescription></SheetHeader>{selected&&<div className="sheet-body"><div className="code-box">ID для оплаты: {selected.id}</div><h3>Первый источник</h3><p>{cmap.get(leadSource(data,selected,scope.asOf)?.campaignId??'')??'Неизвестен'}</p><form onSubmit={e=>{e.preventDefault();void save('lead',selected,()=>setSelected(null));}} className="form-grid"><Picker label="Этап" value={selected.stage} onChange={v=>setSelected({...selected,stage:v as Stage})} items={stages}/><label className="field">Ответственный<Input value={selected.owner} onChange={e=>setSelected({...selected,owner:e.target.value})}/></label><div className="full field"><span>Курс заявки</span><strong>{selected.course||'Пока не выбран'}</strong></div><label className="field full">Заметка<Textarea value={selected.note} onChange={e=>setSelected({...selected,note:e.target.value})}/></label><div className="actions full"><Button type="submit" disabled={busy}>Сохранить</Button><Button type="button" variant="outline" onClick={()=>paymentDraft(selected)}>Зарегистрировать оплату</Button></div></form><h3>Путь уникальных ссылок</h3>{data.events.filter(e=>e.mode===mode&&e.userId===selected.userId).sort((a,b)=>a.at.localeCompare(b.at)).map(e=><p className="muted" key={e.id}>{e.at.slice(0,16).replace('T',' ')} · {e.type==='visit'?'Переход':e.type==='lead'?'Заявка':e.type==='manager_source'?'Источник со слов клиента':'Событие'} · {data.placements.find(p=>p.id===e.placementId)?.channel??'Неизвестно'}</p>)}</div>}</SheetContent></Sheet>
 <Dialog open={!!payment} onOpenChange={v=>{if(!v)setPayment(null);}}><DialogContent><DialogHeader><DialogTitle>Регистрация {mode==='demo'?'тестовой ':''}оплаты</DialogTitle><DialogDescription>Выберите заявку. Курс и посетитель подтягиваются из неё, источник — из сохранённого пути ссылок. Деньги не списываются.</DialogDescription></DialogHeader>{payment&&<form className="form-grid" onSubmit={e=>{e.preventDefault();void save('payment',payment,()=>{setPayment(null);setSelected(null);});}}><label className="field full">Уникальный ID оплаты<Input required value={payment.id} onChange={e=>setPayment({...payment,id:e.target.value})}/></label><div className="full"><Picker label="Заявка" value={payment.leadId??''} onChange={v=>{const l=leads.find(l=>l.id===v);if(l)setPayment({...payment,userId:l.userId,leadId:l.id,course:l.course||payment.course});}} items={leads.map(l=>({value:l.id,label:l.id+' · '+l.course}))}/></div><div className="full"><Picker label="Курс" value={payment.course} onChange={v=>setPayment({...payment,course:v})} items={(leads.find(l=>l.id===payment.leadId)?.course?[payment.course]:data.courses).map(value=>({value,label:value}))}/></div><label className="field">Сумма, ₽<Input required type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:Number(e.target.value)})}/></label><label className="field">Время UTC<Input required type="datetime-local" value={payment.at.slice(0,16)} onChange={e=>setPayment({...payment,at:e.target.value+':00Z'})}/></label><Button type="submit" disabled={busy}>Сохранить оплату</Button></form>}</DialogContent></Dialog>
 <Dialog open={newLead} onOpenChange={setNewLead}><DialogContent><DialogHeader><DialogTitle>Заявка вручную</DialogTitle><DialogDescription>Источник можно указать со слов клиента. Если неизвестен, он остаётся неизвестным.</DialogDescription></DialogHeader><form className="form-grid" onSubmit={addLead}><div className="full"><Picker label="Курс" value={newCourse} onChange={v=>{setNewCourse(v);setSource('unknown');}} items={data.courses.map(value=>({value,label:value}))}/></div><div className="full"><Picker label="Размещение / уникальная ссылка" value={sourceId} onChange={setSource} items={[{value:'unknown',label:'Источник неизвестен'},...data.placements.filter(p=>p.mode===mode&&p.status==='published'&&(!p.courses.length||p.courses.includes(newCourse))).map(p=>({value:p.id,label:(cmap.get(p.campaignId)??p.title)+' · '+p.channel}))]}/></div><label className="field full">Ответственный<Input value={owner} onChange={e=>setOwner(e.target.value)}/></label><Button type="submit" disabled={busy}>Сохранить заявку</Button></form></DialogContent></Dialog>
 <Dialog open={!!refund} onOpenChange={v=>{if(!v)setRefund(null);}}><DialogContent><DialogHeader><DialogTitle>Возврат по оплате</DialogTitle><DialogDescription>Укажите общую возвращённую сумму. Оплата не удаляется; возврат уменьшит ROAS и ROMI.</DialogDescription></DialogHeader>{refund&&<form onSubmit={e=>{e.preventDefault();void save('refund',refund,()=>setRefund(null));}}><Input aria-label="Возвращённая сумма" type="number" min="0" step="0.01" value={refund.amount} onChange={e=>setRefund({...refund,amount:Number(e.target.value)})}/><Button type="submit" className="mt-5" disabled={busy}>Сохранить возврат</Button></form>}</DialogContent></Dialog></>;
}
