'use client';
import {useState}from 'react';
import {Button}from '@/components/ui/button';
import {Input}from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription}from '@/components/ui/dialog';
import {maskUser}from '@/lib/funnel-data';
import type {Workspace,PurchaseIntent,Mode}from '@/lib/types';
export default function PaymentDialog({data,intents,mode,mutate,close,initialIntent}:{data:Workspace;intents:PurchaseIntent[];mode:Exclude<Mode,'historical'>;mutate:(a:string,v:unknown)=>Promise<unknown>;close:()=>void;initialIntent?:string}){
 const initial=intents.find(i=>i.id===initialIntent);
 const[selection,setSelection]=useState(initialIntent??''),[query,setQuery]=useState(''),[course,setCourse]=useState(initial?.course??''),[id,setId]=useState(()=> 'pay_'+crypto.randomUUID()),[amount,setAmount]=useState(''),[at,setAt]=useState(()=>new Date(Math.max(Date.now(),Date.parse(initial?.occurredAt??'')+60000||0)).toISOString().slice(0,16)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const chosen=intents.find(i=>i.id===selection),unknown=selection==='__unknown';
 function pick(value:string){setSelection(value);const i=intents.find(i=>i.id===value);setCourse(i?.course??'');setAt(new Date(Math.max(Date.now(),Date.parse(i?.occurredAt??'')+60000||0)).toISOString().slice(0,16));setError('');}
 async function submit(e:React.SyntheticEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await mutate('payment',{id,mode,purchaseIntentId:chosen?.id??null,userKey:chosen?.userKey??null,unknown,course,amount:Number(amount),at:at+':00Z'});close();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить оплату.');}finally{setBusy(false);}}
 const label=(i:PurchaseIntent)=>{const p=data.placements.find(p=>p.id===i.placementId),c=data.campaigns?.find(c=>c.id===p?.campaignId);return maskUser(i.userKey)+' · '+(p?.title??(i.sourceCode?'Непривязанный источник':'Органический источник'))+' · '+(c?.name??'')+' · '+i.occurredAt.slice(0,16);};
 const filtered=intents.filter(i=>!query||label(i).toLowerCase().includes(query.toLowerCase())||i.id===selection);
 return <Dialog open onOpenChange={v=>{if(!v)close();}}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Зарегистрировать оплату</DialogTitle><DialogDescription>{mode==='demo'?'Подтверждённая оплата в вымышленном демо.':'Подтверждение факта оплаты менеджером.'} Событие payment_click само по себе не является оплатой.</DialogDescription></DialogHeader><form onSubmit={submit} className="form-grid"><label className="field full">Поиск заявки<Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Маскированный ключ, размещение или кампания"/></label><label className="field full">Заявка / пользователь<select className="native-select" required value={selection} onChange={e=>pick(e.target.value)}><option value="">Выберите заявку из событий бота</option><option value="__unknown">Источник неизвестен / вне бота</option>{filtered.map(i=><option key={i.id} value={i.id}>{label(i)}</option>)}</select></label><label className="field full">Подтверждённый курс<select className="native-select" required disabled={!!chosen?.course} value={course} onChange={e=>setCourse(e.target.value)}><option value="">Выберите курс</option>{data.courses.map(c=><option key={c} value={c}>{c}</option>)}</select>{chosen&&!chosen.course&&<span className="muted">Бот не сообщает выбранный курс. Укажите фактически оплаченный.</span>}</label><label className="field full">Payment ID<Input required maxLength={100} value={id} onChange={e=>setId(e.target.value)} placeholder="Внешний ID или сгенерированный идентификатор"/></label><label className="field">Сумма, ₽<Input type="number" required min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field">Дата оплаты UTC<Input type="datetime-local" required value={at} onChange={e=>setAt(e.target.value)}/></label><p className="callout full">Источник не фиксируется вручную: на экране «Результаты» сумму распределят по bot starts этого userKey. Оплата вне бота останется в «Источник неизвестен».</p>{error&&<div className="error-box full" role="alert">{error}</div>}<div className="actions full"><Button type="submit" disabled={busy||!data.integration?.isAdmin||!selection||!course}>{busy?'Сохраняю…':'Подтвердить оплату'}</Button><Button variant="outline" type="button" onClick={close}>Отмена</Button></div></form></DialogContent></Dialog>;
}
