'use client';
import {useState}from 'react';
import {ChevronDown}from 'lucide-react';
import {Button}from '@/components/ui/button';
import {Input}from '@/components/ui/input';
import {Checkbox}from '@/components/ui/checkbox';
import {Popover,PopoverTrigger,PopoverContent}from '@/components/ui/popover';
import {Picker}from './common';
import {campaigns,defaults}from '@/lib/reporting';
import type{Selection,ReportScope,Workspace,Mode}from '@/lib/types';
export function MultiPicker({label,values,onChange,items}:{label:string;values:Selection;onChange:(v:Selection)=>void;items:{value:string;label:string}[]}){
 const[q,setQ]=useState('');const visible=items.filter(i=>i.label.toLowerCase().includes(q.toLowerCase()));
 function toggle(v:string){onChange(values?.includes(v)?values.filter(x=>x!==v):[...(values??[]),v]);}
 return <Popover><PopoverTrigger render={<Button variant="outline" className="multi-trigger"/>}>{values===null?'Все '+label.toLowerCase():values.length===1?items.find(i=>i.value===values[0])?.label??values[0]:label+': '+values.length}<ChevronDown size={15}/></PopoverTrigger><PopoverContent align="start" className="multi-menu"><Input aria-label={'Поиск: '+label} placeholder="Поиск" value={q} onChange={e=>setQ(e.target.value)}/><label className="check-option"><Checkbox checked={values===null} onCheckedChange={()=>onChange(null)}/><span>Все {label.toLowerCase()}</span></label><div className="check-list">{visible.map(i=><label className="check-option" key={i.value}><Checkbox checked={values?.includes(i.value)??false} onCheckedChange={()=>toggle(i.value)}/><span>{i.label}</span></label>)}</div><div className="actions justify-between border-t pt-3"><span className="muted">{values===null?'Без ограничений':values.length+' выбрано'}</span><Button size="sm" variant="ghost" onClick={()=>onChange(null)}>Сбросить</Button></div></PopoverContent></Popover>;
}
export default function ScopeBar({data,scope,setScope,calendar=false}:{data:Workspace;scope:ReportScope;setScope:(s:ReportScope)=>void;calendar?:boolean}){
 const p=data.placements.filter(p=>scope.mode==='all'||p.mode===scope.mode),cs=campaigns(data,scope.mode==='all'?undefined:scope.mode);
 return <section className="scope-bar"><div className="scope-heading"><strong>{calendar?'Что показать в календаре':'Когорта размещений'}</strong><span className="muted">{calendar?'Выберите несколько каналов и курсов':'Размещения за период → их заявки и последующие оплаты до даты расчёта'}</span></div><div className="filters"><Picker value={scope.mode} onChange={v=>setScope({...defaults(v as Mode|'all'),courses:scope.courses})} items={[...(calendar?[{value:'all',label:'История + план'}]:[]),{value:'historical',label:'Исторический кейс'},{value:'demo',label:'Синтетическое демо'},{value:'live',label:'Новый запуск'}]}/><MultiPicker label="Каналы" values={scope.channels} onChange={channels=>setScope({...scope,channels})} items={[...new Set(p.map(p=>p.channel))].sort().map(value=>({value,label:value}))}/><MultiPicker label="Курсы" values={scope.courses} onChange={courses=>setScope({...scope,courses})} items={[...data.courses,'Курс не указан'].map(value=>({value,label:value}))}/><MultiPicker label="Кампании" values={scope.campaigns} onChange={campaigns=>setScope({...scope,campaigns})} items={cs.map(c=>({value:c.id,label:c.name}))}/><Button variant="ghost" onClick={()=>setScope({...scope,channels:null,courses:null,campaigns:null})}>Сбросить фильтры</Button></div><div className="filters mt-4"><label className="field">Размещения с<Input type="date" value={scope.from} onChange={e=>{if(e.target.value)setScope({...scope,from:e.target.value});}}/></label><label className="field">Размещения по<Input type="date" value={scope.to} min={scope.from} onChange={e=>{if(e.target.value)setScope({...scope,to:e.target.value});}}/></label>{!calendar&&<label className="field">Оплаты учтены по<Input type="date" value={scope.asOf} onChange={e=>{if(e.target.value)setScope({...scope,asOf:e.target.value});}}/></label>}<p className="scope-note">{scope.mode==='demo'?'Даты и экономика демо вымышлены. Возвраты учтены в текущем состоянии.':scope.mode==='historical'?'Источники покупателей, лиды и расходы в исходном кейсе отсутствуют.':'Выбранные источники применяются ко всем экранам. Возвраты учтены в текущем состоянии.'}</p></div>{scope.to<scope.from&&<p className="text-red-700 mt-3">Дата окончания должна быть после начала.</p>}</section>;
}
