'use client';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription}from '@/components/ui/sheet';
import {Button}from '@/components/ui/button';
import {maskUser}from '@/lib/funnel-data';
import {money,number}from './common';
import type {FunnelGroup,PaymentRow}from '@/lib/funnel-report';
import type {Workspace,PurchaseIntent}from '@/lib/types';
export default function SourceDrawer({group,data,payments,intents,close,register}:{group:FunnelGroup;data:Workspace;payments:PaymentRow[];intents:PurchaseIntent[];close:()=>void;register:(id:string)=>void}){
 const users=[...new Set(group.botEvents.map(e=>e.userKey))].slice(-20);
 return <Sheet open onOpenChange={v=>{if(!v)close();}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{group.name}</SheetTitle><SheetDescription>Диагностика источника и наблюдаемого пути</SheetDescription></SheetHeader><div className="sheet-body"><p>{group.detail}</p><p>Курсы: {group.courses.join(', ')||'Не определены'}</p><div className="placement-kpis"><div><span>Bot start: события / люди</span><strong>{group.botStartsRaw} / {group.botStartsUsers}</strong></div><div><span>К покупке: события / люди</span><strong>{group.intentsRaw} / {group.intentUsers}</strong></div><div><span>Оплаты / сумма после возвратов</span><strong>{group.paymentsCount} / {money(group.netRevenue)}</strong></div><div><span>Start → заявка</span><strong>{group.startToIntentPct===null?'—':number(group.startToIntentPct)+'%'}</strong></div></div>{group.placementIds.map(id=>{const p=data.placements.find(p=>p.id===id);return p&&<section key={id}><h3>{p.title}</h3><p className="muted">{p.channel} · {data.campaigns?.find(c=>c.id===p.campaignId)?.name}</p><p className="code-box">botTrackingKey: {p.botTrackingKey??'—'}<br/>source_code: {p.botSourceCode??'—'}</p>{p.mode==='demo'&&<p className="muted">Источник событий демо синтетический; рабочий bot-link сохранён отдельно.</p>}{p.postUrl&&<a href={p.postUrl} target="_blank" rel="noreferrer">Исходный Telegram-пост</a>}</section>;})}<h3>Последние анонимные пользователи</h3><p className="muted">До 20 пользователей в выбранном срезе. Браузеры с Telegram-пользователями не сопоставляются.</p>{!users.length&&<p className="muted">Нет наблюдаемых событий бота.</p>}{users.map(key=>{const events=group.botEvents.filter(e=>e.userKey===key),isPaid=payments.some(r=>r.payment.userKey===key),i=intents.find(i=>i.userKey===key&&(i.placementId?group.placementIds.includes(i.placementId):i.sourceCode===events[0]?.sourceCode));return <section className="source-user" key={key}><strong>{maskUser(key)}</strong><p className="muted">Подтверждённая оплата: {isPaid?'да':'нет'}</p>{events.slice(-8).map(e=><p key={e.id} className="muted">{e.eventType==='start'?'Start':'Передано менеджеру'} · {e.occurredAt.replace('T',' ').slice(0,19)} UTC<br/><span className="source-code">{e.sourceCode??'Organic / пустой источник'}</span></p>)}{i&&data.integration?.isAdmin&&<Button variant="outline" size="sm" onClick={()=>register(i.id)}>Зарегистрировать оплату</Button>}</section>;})}<p className="table-note">payment_click — намерение купить. CRM-стадии и редактирование пути здесь отсутствуют.</p></div></SheetContent></Sheet>;
}
