'use client';
import {useState} from 'react';
import {Bot,RefreshCw,Play,Pause} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
interface Status {configured:boolean;connected?:boolean;username?:string;pending?:number;lastError?:string;config:{enabled:boolean;welcome:string;managerUrl:string};}
export default function TelegramControl({admin,load}:{admin:boolean;load:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[status,setStatus]=useState<Status|null>(null),[welcome,setWelcome]=useState(''),[manager,setManager]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/telegram',{cache:'no-store'}),s=await r.json() as Status&{error?:string};if(!r.ok)throw new Error(s.error);setStatus(s);setWelcome(s.config.welcome);setManager(s.config.managerUrl);}catch(e){setError(e instanceof Error?e.message:'Не удалось проверить бота.');}finally{setBusy(false);}}
 async function action(value:string){setBusy(true);setError('');try{const r=await fetch('/api/telegram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:value,welcome,managerUrl:manager})}),body=await r.json() as {error?:string};if(!r.ok)throw new Error(body.error);await refresh();await load();toast.success(value==='save'?'Настройки сохранены':value==='enable'?'Бот подключён к сайту':'Бот поставлен на паузу');}catch(e){setError(e instanceof Error?e.message:'Не удалось изменить бота.');}finally{setBusy(false);}}
 return <><Button variant="outline" size="sm" disabled={!admin} title={admin?'Управление Telegram-ботом':'Войдите в команду для управления ботом'} onClick={()=>{setOpen(true);void refresh();}}><Bot size={16}/>Бот</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Telegram-бот</DialogTitle><DialogDescription>Работает на сервере Cloudflare. Управление доступно с любого компьютера после входа в команду.</DialogDescription></DialogHeader>{status&&<><div className="info-strip"><p><strong>@{status.username??'tracker_marketing_bot'} · {status.connected?'Подключён и принимает события':status.config.enabled?'Подключение требует проверки':'На паузе'}</strong></p><p>Start и намерения купить поступают в «Воронку» автоматически. Ноутбук можно выключить.</p><p>В очереди Telegram: {status.pending??'—'}{status.lastError?' · Последняя ошибка: '+status.lastError:''}</p></div><div className="actions mt-3"><Button disabled={busy||!status.configured||!!status.connected} onClick={()=>{void action('enable');}}><Play size={16}/>Включить / подключить</Button><Button variant="outline" disabled={busy||!status.config.enabled} onClick={()=>{void action('pause');}}><Pause size={16}/>Пауза</Button><Button variant="ghost" disabled={busy} onClick={()=>{void refresh();}} aria-label="Проверить статус бота"><RefreshCw size={16}/></Button></div><a href="/api/telegram/events.csv" target="_blank" rel="noreferrer" download className="text-sm underline mt-3 block">Скачать события CSV (обезличенные ID)</a><p className="muted mt-3">Пауза отключает доставку; очередь не удаляется. После включения накопленные события будут обработаны. Python polling одновременно запускать нельзя.</p><form className="mt-4" onSubmit={e=>{e.preventDefault();void action('save');}}><label className="field">Ответ после Start<textarea className="native-select min-h-28 p-3" required maxLength={800} value={welcome} onChange={e=>setWelcome(e.target.value)}/></label><label className="field mt-3">Менеджер<Input required value={manager} onChange={e=>setManager(e.target.value)} placeholder="https://t.me/username"/></label><p className="muted mt-2">Новые настройки применяются к следующим ответам. Ссылки календаря сохраняют источник. Клик по покупке не создаёт оплату.</p><Button type="submit" className="mt-3" disabled={busy}>Сохранить настройки</Button></form></>}{busy&&!status&&<p>Проверяем подключение…</p>}{error&&<p className="error-box" role="alert">{error}</p>}</DialogContent></Dialog></>;
}
