'use client';
import {Copy,ExternalLink,Download}from 'lucide-react';
import {toast}from 'sonner';
import {Button}from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell}from '@/components/ui/table';
import type{Workspace,ReportScope}from '@/lib/types';
import {report,groupReport,has,NONE}from '@/lib/reporting';
import {millis}from '@/lib/attribution';
import {ModeNote,money,number,download}from './common';
export default function Tracking({data,scope,setScope,mutate}:{data:Workspace;scope:ReportScope;setScope:(s:ReportScope)=>void;mutate:(a:string,v:unknown)=>Promise<unknown>}){
 const mode=scope.mode==='all'?'demo':scope.mode,r=report(data,scope,{model:'last',windowDays:7,halfLifeDays:2,family:false,paymentOffset:0}),groups=groupReport(r,'campaignCourse');
 const places=r.places.filter(p=>(p.courses.length?p.courses:[NONE]).some(c=>has(c,scope.courses))),ids=new Set(places.map(p=>p.id)),events=data.events.filter(e=>e.mode===mode&&e.placementId&&ids.has(e.placementId)&&millis(e.at)<=millis(scope.asOf+'T23:59:59Z'));
 const visits=events.filter(e=>e.type==='visit'),visitorIds=new Set(visits.map(e=>e.userId)),origin=typeof window==='undefined'?'':window.location.origin;
 async function copy(id:string){try{await navigator.clipboard.writeText(origin+'/r/'+id);toast.success('Уникальная ссылка скопирована');}catch{toast.error('Не удалось скопировать; ссылка показана в строке размещения.');}}
 if(mode==='historical')return <><h1>Уникальные ссылки маркетинга</h1><div className="info-strip"><p>В историческом датасете переходы по уникальным ссылкам не наблюдаются. Публичная ссылка на пост — источник текста, а не журнал посетителей. Выберите демо или новый запуск, чтобы увидеть рабочую цепочку.</p></div></>;
 return <><div className="page-heading"><div><div className="eyebrow">ИСТОЧНИК СОХРАНЯЕТСЯ АВТОМАТИЧЕСКИ</div><h1>Ссылки и конверсия</h1><p>Каждое размещение получает отдельный адрес. Путь связывается с заявкой и оплатой внутри приложения.</p></div><Button variant="outline" onClick={()=>download('link-events-'+mode+'.csv',events)}><Download size={16}/>CSV событий</Button></div><ModeNote mode={mode}/><div className="link-steps"><div><span>1</span><strong>Уникальная ссылка</strong><p>Выпускается в карточке календаря.</p></div><div><span>2</span><strong>Переход и заявка</strong><p>Источник сохраняется с посетителем и курсом.</p></div><div><span>3</span><strong>Подтверждённая оплата</strong><p>Менеджер выбирает ID заявки.</p></div><div><span>4</span><strong>Атрибуция и экономика</strong><p>Модель распределяет оплату; расходы дают ROAS и ROMI.</p></div></div><div className="stats"><article><span>Размещения с рабочей ссылкой</span><strong>{places.filter(p=>p.linkIssuedAt).length}</strong><p>Только опубликованные в выбранной когорте</p></article><article><span>Посетившие браузеры</span><strong>{visitorIds.size}</strong><p>{visits.length} переходов; повторы не новые посетители</p></article><article><span>Заявки первого входа</span><strong>{r.leads.length}</strong><p>По выбранным источникам и курсам</p></article><article><span>Оплаты по Last Touch</span><strong>{money(r.rows.reduce((s,a)=>s+a.revenue,0))}</strong><p>После возвратов, без перераспределения скрытых источников</p></article></div>
 <section className="panel"><div className="panel-header"><div><h2>Результат ссылки по кампании и курсу</h2><p>Первый вход определяет источник заявки, последнее подходящее касание — оплаты. Переход по многокурсовому посту учитывается один раз, в «Курс не указан» до выбора курса.</p></div></div><Table><TableHeader><TableRow><TableHead>Кампания / курс</TableHead><TableHead>Переходы / браузеры</TableHead><TableHead>Заявки → оплатили</TableHead><TableHead>Конверсия заявки</TableHead><TableHead>Сумма по модели</TableHead></TableRow></TableHeader><TableBody>{groups.map(g=><TableRow key={g.key}><TableCell><button className="table-cell-action" onClick={()=>setScope({...scope,campaigns:[...g.campaignIds].filter(v=>v!=='unknown').length?[...g.campaignIds]:null,courses:[...g.courses]})}>{g.name}</button><p className="muted">{g.detail}</p></TableCell><TableCell>{g.clicks} / {g.starts.size}</TableCell><TableCell>{g.leads} → {g.cohortBuyers}</TableCell><TableCell>{g.conversion===null?'—':number(g.conversion)+'%'}</TableCell><TableCell>{money(g.netRevenue)}</TableCell></TableRow>)}</TableBody></Table></section>
 <section className="panel"><div className="panel-header"><div><h2>Уникальные ссылки размещений</h2><p>Выпустите адрес в календаре, вставьте в пост. Откройте ссылку, оставьте заявку на курс и затем зарегистрируйте её оплату во вкладке «Заявки и оплаты».</p></div></div><Table><TableHeader><TableRow><TableHead>Размещение</TableHead><TableHead>Курс / кампания</TableHead><TableHead>Переходы</TableHead><TableHead>Ссылка</TableHead></TableRow></TableHeader><TableBody>{places.map(p=><TableRow key={p.id}><TableCell>{p.title}<p className="muted">{p.channel} · {p.startsAt.slice(0,10)}</p></TableCell><TableCell>{p.courses.join(', ')||NONE}<p className="muted">{r.cmap.get(p.campaignId)?.name}</p></TableCell><TableCell>{visits.filter(e=>e.placementId===p.id).length}<p className="muted">{new Set(visits.filter(e=>e.placementId===p.id).map(e=>e.userId)).size} браузеров</p></TableCell><TableCell>{p.linkIssuedAt?<><div className="actions"><Button size="sm" variant="outline" onClick={()=>copy(p.id)}><Copy size={14}/>Копировать</Button><a className="source-link" href={'/r/'+p.id} target="_blank" rel="noreferrer">Открыть <ExternalLink size={14}/></a></div><p className="muted mt-2 break-all">/r/{p.id}</p></>:<Button size="sm" onClick={()=>{void mutate('issue_link',{id:p.id}).catch(()=>{});}}>Выпустить ссылку</Button>}{p.postUrl&&<a href={p.postUrl} target="_blank" rel="noreferrer" className="source-link mt-2">Пост в Telegram <ExternalLink size={14}/></a>}</TableCell></TableRow>)}</TableBody></Table>{!places.length&&<div className="empty">Нет опубликованных размещений по фильтрам. Создайте размещение в календаре и укажите курс.</div>}</section>
 <details className="method-details panel"><summary>Как источник связывается с оплатой</summary><p>Ссылка содержит ID размещения. Сервер записывает переход и случайный ID браузера в базе; cookie сохраняет только этот ID. При отправке формы заявка получает тот же ID и курс. При оплате менеджер выбирает заявку — модель читает её сохранённые переходы до оплаты.</p><p>Несколько ссылок в одном браузере образуют путь. First / Last / Linear / Time Decay распределяют оплату между уникальными кампаниями этого пути. Название источника не угадывается по сумме или дате.</p><p>Без заявки и оплаты переход остаётся посещением. Один браузер не обязательно один человек; блокировка cookie и другое устройство могут разорвать путь. Для прототипа мы допускаем сохранение одного браузера и ID заявки до оплаты.</p><p>Эта демонстрация приватная. Для рекламного запуска аудитории потребуется доступный адрес входной формы и отдельный доступ команды к рабочему пространству; платный сервис для механики не требуется.</p></details></>;
}
