import test from 'node:test';import assert from 'node:assert/strict';
import seed from '../data/seed.json';
import {confirmedPayment,refundPayment}from '../lib/payments';
import {normalizeWorkspace,intentId}from '../lib/funnel-data';
import {funnelReport,defaults,groupReport,report,historicalCoverage,reportingMode,reportingScope}from '../lib/reporting';
import {attribute,HISTORICAL_WARNING}from '../lib/attribution';
import type {Workspace,BotEvent,Options,Placement}from '../lib/types';
const source=seed as unknown as Workspace,opt:Options={model:'linear',windowDays:7,halfLifeDays:2,family:false,paymentOffset:0};
const scope={...defaults('demo'),from:'2026-09-01',to:'2026-09-20',asOf:'2026-09-30'};
function p(id:string,channel='@channel_'+id):Placement{return {...source.placements[0],id,campaignId:'same_campaign',mode:'demo',channel,courses:['A'],status:'published',cost:100,startsAt:'2026-09-09T10:00:00Z',endsAt:'2026-09-09T11:00:00Z',courseShares:undefined,match:'explicit'};}
function data():Workspace{return{placements:[p('a'),p('b')],events:[],botEvents:[],payments:[],leads:[],courses:['A','B'],settings:source.settings,campaigns:[{id:'same_campaign',mode:'demo',name:'One campaign',goal:'',owner:'',extraCost:20,estimatedAdCost:null}],economics:[{id:'eco',mode:'demo',course:'A',deliveryPercent:0,feePercent:0,perSaleCost:0}]};}
function e(id:string,placementId:string|null='a',eventType:BotEvent['eventType']='start',userKey='user_1',occurredAt='2026-09-09T12:00:00Z'):BotEvent{return{id,mode:'demo',placementId,eventType,userKey,occurredAt,sourceCode:placementId?'telegram|channel_'+placementId+'|key_'+placementId:null,socialNetwork:'telegram',channel:placementId?'channel_'+placementId:null,contentId:placementId,importBatchId:'test',mappingStatus:placementId?'mapped':'organic'};}
function sale(d:Workspace){const i=normalizeWorkspace(d).purchaseIntents![0];d.payments=[{id:'pay',mode:'demo',userId:'opaque',userKey:'user_1',purchaseIntentId:i?.id??null,course:'A',amount:1000,at:'2026-09-10T12:00:00Z',status:'paid',source:'synthetic_demo'}];}
void test('Repeated starts/intents have raw counts but one person; global union across placements',()=>{const d=data();d.botEvents=[e('1'),e('2'),e('3'),e('4','a','payment_click'),e('5','a','payment_click'),e('6','b')];const r=funnelReport(d,scope);assert.equal(r.totals.botStartsRaw,4);assert.equal(r.totals.botStartsUnique,1);assert.equal(r.totals.intentsRaw,2);assert.equal(r.totals.intentsUnique,1);assert.equal(r.totals.startToIntentPct,100);assert.equal(r.groups.reduce((n,g)=>n+g.botStartsUsers,0),2);assert.equal(normalizeWorkspace(d).purchaseIntents!.length,1);});
void test('Two people are unique within a placement and no payments yields no paid conversion',()=>{const d=data();d.botEvents=[e('1'),e('2','a','start','user_2')];const r=funnelReport(d,scope);assert.equal(r.totals.botStartsUnique,2);assert.equal(r.totals.intentToPaidPct,null);assert.equal(r.groups.find(g=>g.key==='a')!.botStartsUsers,2);});
void test('Organic/unknown intent never borrows a previous source and stable view IDs survive older imports',()=>{const d=data();d.botEvents=[e('1'),e('2',null,'payment_click'),{...e('3',null,'payment_click'),sourceCode:'telegram|unmapped|offer',mappingStatus:'unmapped'}];const first=normalizeWorkspace(d);assert.equal(first.purchaseIntents!.length,2);assert.ok(first.purchaseIntents!.every(i=>i.placementId===null));const id=first.purchaseIntents![0].id;d.botEvents.push({...e('older',null,'payment_click'),occurredAt:'2026-09-08T12:00:00Z'});assert.ok(normalizeWorkspace(d).purchaseIntents!.some(i=>i.id===id));const r=funnelReport(d,scope);assert.equal(r.diagnostics.organicEvents,2);assert.equal(r.diagnostics.unmappedSources.length,1);});
void test('Four models retain two placements of one campaign, repeated starts never multiply credit',()=>{const d=data();d.botEvents=[e('a1'),e('b1','b','start','user_1','2026-09-10T10:00:00Z'),e('a2','a','start','user_1','2026-09-10T11:00:00Z'),e('intent','a','payment_click')];sale(d);
 assert.equal(attribute(d,'demo',{...opt,model:'first'})[0].placementId,'a');assert.equal(attribute(d,'demo',{...opt,model:'last'})[0].placementId,'a');const lin=attribute(d,'demo',opt);assert.equal(lin.length,2);assert.ok(lin.every(a=>a.weight===.5));const dec=attribute(d,'demo',{...opt,model:'decay'});assert.ok(dec.find(a=>a.placementId==='a')!.weight>dec.find(a=>a.placementId==='b')!.weight);for(const model of ['first','last','linear','decay'] as const){const rs=attribute(d,'demo',{...opt,model});assert.equal(rs.reduce((s,a)=>s+a.revenue,0),1000);assert.equal(rs.reduce((s,a)=>s+a.weight,0),1);}
});
void test('Browser and payment_click never become qualifying touches, even with identical identity strings',()=>{const d=data();d.botEvents=[e('intent','a','payment_click')];d.events=[{id:'web',mode:'demo',userId:'user_1',botUserKey:'user_1',placementId:'a',type:'web_visit',at:'2026-09-09T12:00:00Z'}];sale(d);const r=attribute(d,'demo',opt);assert.equal(r.length,1);assert.equal(r[0].basis,'unknown');assert.equal(r[0].revenue,1000);});
void test('Future, stale, other-user and wrong-course bot starts cannot claim payment',()=>{const d=data();d.botEvents=[e('future','a','start','user_1','2026-09-11T00:00:00Z'),e('stale','a','start','user_1','2026-08-01T00:00:00Z'),e('other','a','start','other'),e('wrong','b')];d.placements[1].courses=['B'];sale(d);assert.equal(attribute(d,'demo',opt)[0].basis,'unknown');});
void test('Explicit unknown payment remains unknown despite other visible starts',()=>{const d=data();d.botEvents=[e('start')];sale(d);d.payments[0].userKey=null;assert.equal(attribute(d,'demo',opt)[0].basis,'unknown');assert.equal(funnelReport(d,scope).groups.find(g=>g.key==='unknown')!.netRevenue,1000);});
void test('Confirmed payment/refunds change only money; full refund retains a past purchaser',()=>{const d=data();d.botEvents=[e('start'),e('intent','a','payment_click')];sale(d);let r=funnelReport(d,scope);assert.equal(r.totals.paidUsersUnique,1);assert.equal(r.totals.intentToPaidPct,100);d.payments[0].refundAmount=400;r=funnelReport(d,scope);assert.equal(r.totals.netRevenue,600);assert.equal(r.totals.paidUsersUnique,1);d.payments[0].status='refunded';r=funnelReport(d,scope);assert.equal(r.totals.netRevenue,0);assert.equal(r.totals.paidUsersUnique,1);assert.equal(normalizeWorkspace(d).purchaseIntents![0].status,'paid');});
void test('All groupings conserve money and costs; channel filter keeps hidden credit',()=>{const d=data();d.botEvents=[e('1'),e('2','b'),e('intent','a','payment_click')];sale(d);const r=report(d,scope,opt);for(const by of ['placement','campaignCourse','campaign','channel','course'] as const){const gs=groupReport(r,by);assert.equal(gs.reduce((s,g)=>s+g.netRevenue,0),1000);assert.equal(gs.reduce((s,g)=>s+g.marketingCost,0),220);}const filtered=report(d,{...scope,channels:['@channel_b']},opt);assert.equal(filtered.rows[0].revenue,500);assert.equal(filtered.rows[0].weight,.5);});
void test('Multi-course intent has unknown course until payment and is counted once',()=>{const d=data();d.placements[0].courses=['A','B'];d.botEvents=[e('start'),e('intent','a','payment_click')];const i=normalizeWorkspace(d).purchaseIntents![0];assert.equal(i.course,null);sale(d);const r=funnelReport(d,scope,'course');assert.equal(r.groups.reduce((n,g)=>n+g.intentsRaw,0),1);assert.equal(r.payments[0].payment.course,'A');assert.equal(intentId(d.botEvents[1]),i.id);});
void test('Historical funnel is empty, scenario banner mandatory and family relevance affects Linear/Decay only',()=>{const d=data();d.placements=d.placements.map((p,i)=>({...p,mode:'historical',match:i?'family_candidate':'explicit'}));d.payments=[{id:'hist',mode:'historical',userId:'old_buyer',course:'A',amount:1000,at:'2026-09-10T12:00:00Z',status:'paid',source:'historical'}];assert.equal(funnelReport(d,{...scope,mode:'historical'}).groups.length,0);assert.equal(funnelReport(d,{...scope,mode:'historical'}).totals.botStartsUnique,0);assert.match(HISTORICAL_WARNING,/НЕ устанавливает фактический источник/);assert.equal(attribute(d,'historical',opt).length,1);for(const model of ['linear','decay'] as const){const rs=attribute(d,'historical',{...opt,model,family:true});assert.ok(Math.abs(rs.find(a=>a.placementId==='b')!.weight-1/3)<1e-9);}assert.equal(attribute(d,'historical',{...opt,model:'last',family:true})[0].weight,1);const h=historicalCoverage(d,{...opt,family:true});assert.equal(h.matched,1);assert.equal(h.explicit,1);assert.equal(h.family,1);assert.ok(h.medianLagDays!>0);});
void test('Normalized synthetic seed is idempotent, shows repeated raw events and no CRM leads',()=>{const one=normalizeWorkspace(source),two=normalizeWorkspace(one);assert.equal(one.botEvents!.length,two.botEvents!.length);assert.equal(one.purchaseIntents!.length,two.purchaseIntents!.length);assert.equal(source.leads.length,0);const r=funnelReport(source,defaults('demo'));assert.ok(r.totals.botStartsRaw>r.totals.botStartsUnique);assert.ok(r.totals.intentsRaw>r.totals.intentsUnique);assert.ok(r.totals.paymentsCount>0);});

void test('Payment validation binds only an existing intent or explicit unknown, and rejects mismatched identity',()=>{const d=data();d.botEvents=[e('intent','a','payment_click')];const i=normalizeWorkspace(d).purchaseIntents![0],v={id:'manual',mode:'demo' as const,purchaseIntentId:i.id,course:'A',amount:1000,at:'2026-09-10T12:00:00Z'};assert.equal(confirmedPayment(d,v).userKey,i.userKey);assert.throws(()=>confirmedPayment(d,{...v,userKey:'different'}),/не соответствует/);assert.throws(()=>confirmedPayment(d,{...v,purchaseIntentId:'missing'}),/не найдена/);assert.throws(()=>confirmedPayment(d,{...v,purchaseIntentId:null}),/явно/);assert.equal(confirmedPayment(d,{...v,purchaseIntentId:null,unknown:true}).userKey,null);assert.throws(()=>confirmedPayment(d,{...v,course:'B'}),/другому курсу/);});
void test('Payment validation rejects duplicate IDs, invalid money/date, and payment before intent',()=>{const d=data();d.botEvents=[e('intent','a','payment_click')];sale(d);const v={id:'pay',mode:'demo' as const,purchaseIntentId:d.payments[0].purchaseIntentId,course:'A',amount:1000,at:'2026-09-10T12:00:00Z'};assert.throws(()=>confirmedPayment(d,v),/уже существует/);for(const amount of [0,-1,NaN,1.001])assert.throws(()=>confirmedPayment(d,{...v,id:'new',amount}));assert.throws(()=>confirmedPayment(d,{...v,id:'new',at:'2026-02-30T12:00:00Z'}),/дата/);assert.throws(()=>confirmedPayment(d,{...v,id:'new',at:'2026-09-08T12:00:00Z'}),/предшествовать/);});
void test('Refund validation changes no identity or intent and blocks historical/out-of-range refunds',()=>{const d=data();sale(d);const p=refundPayment(d,'pay',500);assert.equal(p.refundAmount,500);assert.equal(p.userKey,d.payments[0].userKey);assert.equal(p.purchaseIntentId,d.payments[0].purchaseIntentId);assert.equal(refundPayment(d,'pay',1000).status,'refunded');for(const n of [-1,1001,1.001])assert.throws(()=>refundPayment(d,'pay',n));d.payments[0].mode='historical';assert.throws(()=>refundPayment(d,'pay',0));});

void test('Course filter excludes bot events with no known placement course, without hiding unknown-course payments',()=>{const d=data();d.botEvents=[e('known'),e('organic',null),e('intent',null,'payment_click')];sale(d);d.payments[0].userKey=null;const r=funnelReport(d,{...scope,courses:['A']});assert.equal(r.totals.botStartsRaw,1);assert.equal(r.totals.intentsRaw,0);assert.equal(r.totals.paymentsCount,1);});

void test('Opening reporting from mixed calendar prioritizes live and respects selected campaign/course',()=>{const d=data();d.placements.push({...p('live'),mode:'live',campaignId:'new_launch',courses:['B']});const all={...scope,mode:'all' as const};assert.equal(reportingMode(d,all),'live');assert.equal(reportingMode(d,{...all,campaigns:['same_campaign']}),'demo');assert.equal(reportingMode(d,{...all,courses:['A']}),'demo');assert.equal(reportingMode(d,{...all,courses:['B']}),'live');assert.equal(reportingMode(d,scope),'demo');const selected=reportingScope(d,all);assert.equal(selected.from,all.from);assert.equal(selected.to,all.to);assert.deepEqual(selected.courses,all.courses);d.placements.at(-1)!.startsAt='2026-09-21T12:00:00Z';assert.equal(reportingMode(d,all),'demo');});
