import test from 'node:test';
import assert from 'node:assert/strict';
import seed from '../data/seed.json';
import {botReferral,encodeSource,decodeSource,channelSlug}from '../lib/bot-referral';
import {normalizeBotCsv,botTimestamp,parseCsv,BOT_HEADERS}from '../lib/bot-import';
import {parsePublicPosts,matchingPosts}from '../lib/telegram-public';
import {publicationStatus,pendingPublication}from '../lib/publication-status';
import {botFunnel}from '../lib/bot-funnel';
import {calendarCsv,excelCsv}from '../lib/calendar-export';
import {attribute}from '../lib/attribution';
import type{Placement,Workspace}from '../lib/types';
const source=seed as unknown as Workspace,salt='f'.repeat(64),origin='https://demo.team.workers.dev';
function p(id='p1'):Placement{return {...source.placements[0],id,mode:'live',status:'planned',channel:'@channel_one',startsAt:'2026-09-12T12:00:00Z',endsAt:'2026-09-12T13:00:00Z',courses:['ML про'],postUrl:'',linkIssuedAt:'2026-09-12T10:00:00Z',publishedAt:undefined};}
async function issued(id='p1'){const placement=p(id);return {...placement,...await botReferral(placement)};}
function csv(rows:string[][]){return [BOT_HEADERS,...rows].map(row=>row.map(v=>'"'+v.replaceAll('"','""')+'"').join(',')).join('\r\n');}
function row(source='',event='start',user='123456789',at='2026-09-12 12:00:00'){const [network='',channel='',key='']=source.split('|');return[at,user,'a'.repeat(64),event,source,network,channel,key];}
function data(events:Workspace['events']=[]):Workspace{return{...source,botEvents:[],purchaseIntents:[],placements:[...new Set(events.map(e=>e.placementId).filter(Boolean))].map(id=>p(id!)),leads:[],payments:[],events};}
void test('Observed bot payload decodes exactly, Cyrillic encoding round-trips',()=>{const fixture='d2Vic2l0ZXzQn9C-0YHRgtGD0L_QsNGI0LrQuHxzdW1tZXJfb2ZmZXI';assert.equal(decodeSource(fixture),'website|Поступашки|summer_offer');assert.equal(encodeSource(decodeSource(fixture)),fixture);});
void test('Placement sources are short, stable and distinct; channels normalize',async()=>{const a=await issued(),b=await issued('p2'),r=await botReferral(a);assert.equal(a.botStartParam,r.botStartParam);assert.notEqual(a.botTrackingKey,b.botTrackingKey);assert.ok(a.botStartParam!.length<=64);assert.equal(channelSlug(' @Channel_One '),'channel_one');assert.equal(decodeSource(a.botStartParam!),a.botSourceCode);});
void test('Long sources fail instead of silently truncating; preview is a separate test source',async()=>{await assert.rejects(botReferral({...p(),channel:'@a'+'b'.repeat(31)}),/64/);const live=await issued(),preview=await botReferral(live,undefined,true);assert.notEqual(preview.botStartParam,live.botStartParam);assert.ok(preview.botSourceCode.split('|')[2].startsWith('test_'));});
void test('Exact CSV headers, quoted commas and malformed rows are handled',()=>{assert.deepEqual(parseCsv(csv([row('website|Канал, один|offer')])),[row('website|Канал, один|offer')]);assert.throws(()=>parseCsv('timestamp,event\n1,start'),/8 колонок/);assert.throws(()=>parseCsv(BOT_HEADERS.join(',')+'\n"bad'),/кавычки/);});
void test('Naive timestamps require explicit timezone and normalize to UTC',()=>{assert.equal(botTimestamp('2026-09-12 12:00:00','UTC+03:00'),'2026-09-12T09:00:00.000Z');assert.equal(botTimestamp('2026-09-12T12:00:00+03:00',''),'2026-09-12T09:00:00.000Z');assert.throws(()=>botTimestamp('2026-09-12 12:00:00',''),/часовой пояс/);assert.throws(()=>botTimestamp('2026-02-30 12:00:00','UTC'),/Несуществующая/);});
void test('CSV IDs are HMACed; timestamps and duplicates produce stable IDs without raw identity',async()=>{const a=await issued(),text=csv([row(a.botSourceCode),row(a.botSourceCode)]),n=await normalizeBotCsv(text,'UTC',salt,[a]),repeat=await normalizeBotCsv(text,'UTC',salt,[a]);assert.equal(n.events.length,1);assert.equal(n.duplicates,1);assert.equal(n.events[0].id,repeat.events[0].id);assert.equal(n.events[0].placementId,a.id);assert.equal(n.events[0].identityBasis,'telegram_id_hmac');assert.equal(n.events[0].botUserKey!.length,64);assert.ok(!JSON.stringify(n.events).includes('123456789'));assert.ok(!JSON.stringify(n.sampleRows).includes('123456789'));});
void test('Salt controls identity; missing ID only allows an existing username hash',async()=>{const a=await issued(),text=csv([row(a.botSourceCode)]),x=await normalizeBotCsv(text,'UTC',salt,[a]),y=await normalizeBotCsv(text,'UTC','z'.repeat(64),[a]);assert.notEqual(x.events[0].botUserKey,y.events[0].botUserKey);const r=row(a.botSourceCode,'start','');assert.equal((await normalizeBotCsv(csv([r]),'UTC',salt,[a])).events[0].identityBasis,'username_hash');r[2]='raw_username';assert.equal((await normalizeBotCsv(csv([r]),'UTC',salt,[a])).errors.length,1);});
void test('Unknown, legacy, empty, conflicting and demo sources never invent a live placement',async()=>{const a=await issued(),rows=[row('telegram|unknown_channel|unknownkey'),row('website|Поступашки|summer_offer'),row(''),row(a.botSourceCode)],n=await normalizeBotCsv(csv(rows),'UTC',salt,[{...a,mode:'demo'}]);assert.equal(n.mapped,0);assert.equal(n.unmapped,4);assert.equal(n.organic,1);assert.ok(n.events.every(e=>e.placementId===null&&e.mode==='live'));const wrong=row(a.botSourceCode);wrong[7]='other_key';const canonical=await normalizeBotCsv(csv([wrong]),'UTC',salt,[a]);assert.equal(canonical.mapped,1);assert.ok(canonical.warnings.length);});
void test('Preview bot events are excluded; unsupported events reject',async()=>{const a=await issued(),preview=await botReferral(a,undefined,true),n=await normalizeBotCsv(csv([row(preview.botSourceCode),row(a.botSourceCode,'paid')]),'UTC',salt,[a]);assert.equal(n.skippedTests,1);assert.equal(n.events.length,0);assert.equal(n.errors.length,1);});
void test('Unique funnel distinguishes 13 starts/8 intents from four people and 100% conversion',async()=>{const a=await issued(),rows=Array.from({length:13},(_,i)=>row(a.botSourceCode,'start',String(100+i%4),'2026-09-12 12:'+String(i).padStart(2,'0')+':00'));rows.push(...Array.from({length:8},(_,i)=>row(a.botSourceCode,'payment_click',String(100+i%4),'2026-09-12 13:'+String(i).padStart(2,'0')+':00')));const n=await normalizeBotCsv(csv(rows),'UTC',salt,[a]),f=botFunnel(data(n.events),[a.id]);assert.equal(f.startEvents,13);assert.equal(f.intentEvents,8);assert.equal(f.uniqueStarters,4);assert.equal(f.uniqueIntentUsers,4);assert.equal(f.conversion,100);assert.ok(Math.abs(f.eventConversion!-800/13)<1e-9);});
void test('Bot totals deduplicate people across posts and warn for intent without start',async()=>{const a=await issued(),b=await issued('p2'),n=await normalizeBotCsv(csv([row(a.botSourceCode),row(b.botSourceCode),row(b.botSourceCode,'payment_click','999')]),'UTC',salt,[a,b]),f=botFunnel(data(n.events),[a.id,b.id]);assert.equal(f.uniqueStarters,1);assert.equal(f.intentWithoutStart,1);assert.equal(botFunnel(data(),[]).conversion,null);});
void test('Purchase intent never creates Payment or financial attribution even with matching IDs',async()=>{const a=await issued(),n=await normalizeBotCsv(csv([row(a.botSourceCode,'payment_click')]),'UTC',salt,[a]),d=data(n.events);assert.equal(d.payments.length,0);d.placements=[{...a,status:'published'}];d.payments=[{id:'pay',mode:'live',userId:n.events[0].userId,course:'ML про',amount:10000,at:'2026-09-13T12:00:00Z',source:'confirmed',status:'paid'}];assert.equal(attribute(d,'live',{model:'last',windowDays:7,halfLifeDays:2,family:false,paymentOffset:0})[0].campaignId,'unknown');});
function html(link:string,time='2026-09-12T12:05:00+00:00',id=42){return '<div data-post="channel_one/'+id+'"><a href="'+link+'">Купить</a><time datetime="'+time+'"></time></div>';}
void test('Public Telegram parsing decodes links and matches only the exact canonical placement URL',()=>{const a=p(),posts=parsePublicPosts(html(origin+'/r/p1')+html(origin+'/r/p10',undefined,43)+html('https://evil.example/r/p1',undefined,44),'@channel_one');const matches=matchingPosts(posts,a,origin);assert.equal(matches.length,1);assert.equal(matches[0].postUrl,'https://t.me/channel_one/42');assert.equal(parsePublicPosts(html(origin+'/r/p1?x=1&amp;y=2'),'channel_one')[0].links[0],origin+'/r/p1?x=1&y=2');});
void test('Publication windows exclude early/late/test posts and keep earliest duplicate',()=>{const a=p(),posts=parsePublicPosts(html(origin+'/r/p1','2026-09-12T11:44:00Z')+html(origin+'/r/p1','2026-09-12T14:01:00Z',43)+html(origin+'/r/p1?preview=1',undefined,44)+html(origin+'/r/p1','2026-09-12T12:15:00Z',45)+html(origin+'/r/p1','2026-09-12T12:10:00Z',46),'channel_one'),matches=matchingPosts(posts,a,origin);assert.equal(matches.length,2);assert.equal(matches[0].messageId,46);});
void test('Lifecycle is derived, cancelled does not scan; factual time does not move planned day',()=>{const a=p(),before=Date.parse(a.startsAt)-16*60000,after=Date.parse(a.startsAt)+121*60000;assert.equal(publicationStatus({...a,linkIssuedAt:undefined},before),'Нужна ссылка');assert.equal(publicationStatus(a,before),'Запланировано');assert.equal(publicationStatus(a,Date.parse(a.startsAt)),'Ожидает публикации');assert.ok(pendingPublication(a,Date.parse(a.startsAt)));assert.equal(publicationStatus(a,after),'Не найден автоматически');assert.ok(!pendingPublication({...a,status:'cancelled'},Date.parse(a.startsAt)));assert.equal(publicationStatus({...a,postUrl:'https://t.me/channel_one/42',publishedAt:'2026-09-12T13:00:00Z'},after),'Опубликовано');});
void test('Excel calendar CSV has BOM, semicolon, CRLF, human columns and formula protection',async()=>{const a=await issued(),d=data();d.placements=[a];d.campaigns=[{id:a.campaignId,mode:'live',name:'=SUM(A1)',goal:'test',owner:'',extraCost:null,estimatedAdCost:null}];const text=calendarCsv(d,[a],origin,()=>({payments:0,revenue:0}));assert.ok(text.startsWith('\uFEFF'));assert.ok(text.includes(';'));assert.ok(text.endsWith('\r\n'));assert.ok(text.includes("'=SUM(A1)"));assert.ok(text.includes("'@channel_one"));assert.ok(text.includes(origin+'/r/p1'));assert.ok(!text.includes('botUserKey'));assert.ok(!text.includes('['));assert.ok(excelCsv([['a;"b\nc']]).includes('a;""b\nc'));});
void test('Streaming body guard enforces limits without trusting content-length',async()=>{const {limitedBody}=await import('../lib/request-limit');await assert.rejects(limitedBody(new Request('https://team.example',{method:'POST',body:'abcdef'}),3),/Слишком большой/);assert.equal(new TextDecoder().decode(await limitedBody(new Request('https://team.example',{method:'POST',body:'abc'}),3)),'abc');});
