import test from 'node:test';import assert from 'node:assert/strict';
import seed from '../data/seed.json';
import {report,groupReport,defaults,contribution,visibleIntents}from '../lib/reporting';
import {attribute}from '../lib/attribution';
import type{Workspace,Placement,Options}from '../lib/types';
const source=seed as unknown as Workspace,opt:Options={model:'linear',windowDays:14,halfLifeDays:2,family:false,paymentOffset:0};
function data():Workspace{return{placements:[],leads:[],events:[],payments:[],courses:['A','B'],settings:source.settings,campaigns:[{id:'c1',mode:'demo',name:'C1',goal:'test',owner:'',extraCost:200,estimatedAdCost:null},{id:'c2',mode:'demo',name:'C2',goal:'test',owner:'',extraCost:0,estimatedAdCost:null}],economics:[{id:'a',mode:'demo',course:'A',deliveryPercent:30,feePercent:2,perSaleCost:500},{id:'b',mode:'demo',course:'B',deliveryPercent:50,feePercent:0,perSaleCost:0}]};}
function p(id:string,campaignId='c1',courses=['A']):Placement{return{...source.placements[0],id,campaignId,mode:'demo',channel:'@'+id,courses,match:'explicit',status:'published',cost:1000,startsAt:'2026-09-12T10:00:00Z',endsAt:'2026-09-12T20:00:00Z',courseShares:undefined};}
const scope={...defaults('demo'),from:'2026-09-12',to:'2026-09-20',asOf:'2026-09-30'};
function sale(d:Workspace){d.payments=[{id:'pay',mode:'demo',userId:'u',course:'A',amount:10000,at:'2026-09-18T12:00:00Z',status:'paid',source:'test'}];d.events=d.placements.map((p,i)=>({id:p.id,mode:'demo',userId:'u',placementId:p.id,type:'bot_start',at:i?'2026-09-17T12:00:00Z':'2026-09-14T12:00:00Z'}));}
void test('A multichannel filter does not renormalize hidden campaign credit',()=>{const d=data();d.placements=[p('p1'),p('p2','c2')];sale(d);const full=report(d,scope,opt);assert.equal(full.rows.reduce((n,a)=>n+a.revenue,0),10000);const selected=report(d,{...scope,channels:['@p2']},opt);assert.equal(selected.rows[0].weight,.5);assert.equal(selected.rows[0].revenue,5000);});
void test('Multi-course budgets split once and campaign totals conserve every ruble',()=>{const d=data();d.placements=[p('p1','c1',['A','B']),p('p2','c1',['A','B'])];d.placements[0].courseShares={A:.75,B:.25};const r=report(d,scope,opt);const c=groupReport(r,'course');assert.equal(c.find(g=>g.name==='A')!.marketingCost,1375);assert.equal(c.find(g=>g.name==='B')!.marketingCost,825);assert.equal(groupReport(r,'campaign')[0].marketingCost,2200);});
void test('Future cohort cannot be marked as an advertising loss',()=>{const d=data();d.placements=[p('p1')];const g=groupReport(report(d,{...scope,asOf:'2026-09-13'},opt,7),'campaign')[0];assert.equal(g.mature,false);assert.equal(g.romi,null);assert.equal(g.roas,null);assert.equal(g.reason,'Ожидаем оплаты');});
void test('ROAS needs ad cost, ROMI additionally needs other marketing and course costs',()=>{const d=data();d.placements=[p('p1')];sale(d);d.campaigns![0].extraCost=null;const g=groupReport(report(d,scope,opt),'campaign')[0];assert.equal(g.roas,10);assert.equal(g.romi,null);});
void test('Course economics includes delivery, fees and sale cost before marketing',()=>{const d=data();d.placements=[p('p1')];sale(d);assert.ok(Math.abs(contribution(d,'demo',d.payments[0])!-6300)<1e-9);const g=groupReport(report(d,scope,opt),'campaign')[0];assert.ok(Math.abs(g.romi!-425)<1e-9);assert.ok(Math.abs(g.breakEvenRevenue!-1200/.63)<1e-9);});
void test('Refund reduces revenue but a per-sale service cost does not disappear',()=>{const d=data();d.placements=[p('p1')];sale(d);d.payments[0].refundAmount=2500;let g=groupReport(report(d,scope,opt),'campaign')[0];assert.equal(g.netRevenue,7500);assert.equal(g.refunds,2500);assert.equal(g.contribution,4600);d.payments[0].status='refunded';g=groupReport(report(d,scope,opt),'campaign')[0];assert.equal(g.netRevenue,0);assert.equal(g.contribution,-500);assert.equal(g.uniqueBuyers,1);});
void test('Intent source and conversion do not change with payment model',()=>{const d=data();d.placements=[p('p1'),p('p2','c2')];sale(d);d.events.push({id:'intent',mode:'demo',userId:'u',placementId:'p1',type:'bot_payment_click',at:'2026-09-14T12:01:00Z'});const a=groupReport(report(d,scope,{...opt,model:'first'}),'campaign'),b=groupReport(report(d,scope,{...opt,model:'last'}),'campaign');assert.equal(a.find(g=>g.name==='C1')!.leads,1);assert.equal(b.find(g=>g.name==='C1')!.leads,1);assert.equal(b.find(g=>g.name==='C1')!.conversion,100);assert.equal(b.find(g=>g.name==='C2')!.netRevenue,10000);});
void test('Unrelated course visits cannot claim a course payment',()=>{const d=data();d.placements=[p('p1','c1',['B'])];sale(d);assert.equal(attribute(d,'demo',opt)[0].campaignId,'unknown');});
void test('All four grouping levels conserve selected costs and allocated receipts',()=>{const d=data();d.placements=[p('p1'),p('p2','c2')];sale(d);const r=report(d,scope,opt);for(const group of ['course','campaign','campaignCourse','channel'] as const){const g=groupReport(r,group);assert.equal(g.reduce((s,g)=>s+g.marketingCost,0),2200);assert.equal(g.reduce((s,g)=>s+g.netRevenue,0),10000);}});
void test('Lead filters support several courses and channels at the same time',()=>{const d=data();d.placements=[p('p1'),p('p2','c2',['B'])];d.events=[{id:'i1',mode:'demo',userId:'u1',placementId:'p1',type:'bot_payment_click',at:'2026-09-14T00:00:00Z'},{id:'i2',mode:'demo',userId:'u2',placementId:'p2',type:'bot_payment_click',at:'2026-09-14T00:00:00Z'}];assert.equal(visibleIntents(d,{...scope,courses:['A','B'],channels:['@p1','@p2']}).length,2);assert.equal(visibleIntents(d,{...scope,courses:[]}).length,0);});

void test('Placement detail preserves hidden credit and apportions shared campaign costs once',()=>{const d=data();d.placements=[p('p1'),p('p2','c1'),p('p3','c2')];sale(d);d.events.push({id:'intent',mode:'demo',userId:'u',placementId:'p1',type:'bot_payment_click',at:'2026-09-14T12:01:00Z'});const r=report(d,{...scope,placements:['p2'],channels:['@p2'],campaigns:['c1']},opt);assert.ok(Math.abs(r.rows[0].revenue-10000/3)<1e-9);assert.equal(r.rows[0].weight,1/3);const g=groupReport(r,'campaign')[0];assert.equal(g.marketingCost,1100);assert.equal(g.leads,0);});

void test('A multi-course click is counted once without guessing a chosen course',()=>{const d=data();d.placements=[p('p1','c1',['A','B'])];d.events=[{id:'v',mode:'demo',userId:'u',placementId:'p1',type:'web_visit',at:'2026-09-14T12:00:00Z'},{id:'a',mode:'demo',userId:'u',placementId:'p1',type:'bot_payment_click',course:'A',at:'2026-09-14T12:01:00Z'}];const g=groupReport(report(d,scope,opt),'course');assert.equal(g.reduce((s,g)=>s+g.clicks,0),1);assert.equal(g.find(g=>g.name==='Курс не указан')!.clicks,1);assert.equal(g.find(g=>g.name==='A')!.clicks,0);assert.equal(g.find(g=>g.name==='Курс не указан')!.messages.size,1);});
