'use client';
import {use,useEffect,useState}from 'react';
import {Button}from '@/components/ui/button';
import {Picker,money}from '@/components/marketing/common';
import type{Workspace,Placement}from '@/lib/types';
export default function Visit({params}:{params:Promise<{placementId:string}>}){
 const{placementId}=use(params),[p,setP]=useState<Placement|null>(null),[courses,setCourses]=useState<string[]>([]),[course,setCourse]=useState(''),[leadId,setLead]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/workspace').then(r=>r.json() as Promise<Workspace>).then((d:Workspace)=>{const found=d.placements.find(p=>p.id===placementId&&p.mode!=='historical'&&p.status==='published'&&p.linkIssuedAt);if(!found)throw Error('Размещение недоступно');setP(found);const list=found.courses.length?found.courses:d.courses;setCourses(list);setCourse(list[0]);}).catch(e=>setError(e.message));},[placementId]);
 async function submit(){setBusy(true);setError('');try{const r=await fetch('/api/visit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({placementId,course})}),b=await r.json() as {error?:string;leadId:string};if(!r.ok)throw Error(b.error);setLead(b.leadId);}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}}
 return <main className="entry-page"><div className="brand text-[#1b2842]"><span className="brand-mark">П</span><div>Поступашки<small>Курсы для карьеры</small></div></div><section className="entry-card"><span className={'pill '+(p?.mode==='demo'?'purple':'blue')}>{p?.mode==='demo'?'Синтетический сценарий':'Интерес к курсу'}</span><h1 className="mt-5">{leadId?'Заявка сохранена':'Выберите следующий шаг в карьере'}</h1>{error&&<p className="error-box">{error}</p>}{p&&!leadId?<><p>Источник перехода сохранён по уникальной ссылке. Оставьте заявку — она будет связана с этим размещением.</p><Picker label="Курс" value={course} onChange={setCourse} items={courses.map(value=>({value,label:value}))}/><Button onClick={submit} disabled={busy}>{busy?'Сохраняем…':'Оставить заявку на курс'}</Button></>:leadId?<><p>{course}</p><div className="code-box">ID заявки: {leadId}</div><p>Менеджер использует этот ID при регистрации оплаты. Источник сохранится; повторная отправка заявки не создаёт дубликат.</p><a href="/">Открыть рабочее пространство команды</a></>:<p>Загружаем курс…</p>}<p className="muted">{p?.mode==='demo'?'Демо не списывает деньги. Время перехода условно привязано к размещению.':'Эта форма сохраняет заявку; приложение не списывает деньги.'}</p></section></main>;
}
